from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[1]
NB_DIR = ROOT / "notebooks"


def md(text: str):
    return {"cell_type": "markdown", "metadata": {}, "source": text}


def code(text: str):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text,
    }


def write_nb(path: Path, cells):
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.x"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(nb, indent=2), encoding="utf-8")


stage1_cells = [
    md("# Stage 1 - Feature Engineering\nThis notebook performs the exact preliminary split and Stage 1 transformations defined in `pipeline.md`, with all fitting done only on training data."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.impute import SimpleImputer\n"
        "from sklearn.preprocessing import OneHotEncoder, MinMaxScaler\n"
        "from sklearn.decomposition import PCA\n"
        "\n"
        "RANDOM_STATE = 42\n"
        "BASE_DIR = Path.cwd().parent\n"
        "RAW_DIR = BASE_DIR / 'data' / 'raw'\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
        "PLOT_DIR = BASE_DIR / 'outputs' / 'plots' / 'stage1'\n"
        "PROCESSED_DIR.mkdir(parents=True, exist_ok=True)\n"
        "PLOT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "plt.style.use('seaborn-v0_8-whitegrid')\n"
        "sns.set_palette('deep')\n"
        "\n"
        "def save_plot(name: str):\n"
        "    path = PLOT_DIR / f'{name}.png'\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(path, dpi=300, bbox_inches='tight')\n"
        "    print(f'Saved plot: {path}')\n"
    ),
    md("## Preliminary Split\nLoad the raw dataset, separate target variables, and perform the stratified 80/20 split before any feature engineering."),
    code(
        "raw_path = RAW_DIR / 'alternate_credit_raw.csv'\n"
        "df = pd.read_csv(raw_path)\n"
        "print('Raw shape:', df.shape)\n"
        "print(df[['defaulted']].value_counts(normalize=True).rename('rate'))\n"
        "\n"
        "y = df['defaulted'].copy()\n"
        "default_probability = df['default_probability'].copy()\n"
        "X = df.drop(columns=['defaulted', 'default_probability']).copy()\n"
        "\n"
        "X_train, X_test, y_train, y_test, dp_train, dp_test = train_test_split(\n"
        "    X, y, default_probability, test_size=0.2, random_state=RANDOM_STATE, stratify=y\n"
        ")\n"
        "\n"
        "borrower_type_train = X_train['borrower_type'].copy()\n"
        "borrower_type_test = X_test['borrower_type'].copy()\n"
        "print('X_train shape:', X_train.shape, '| X_test shape:', X_test.shape)\n"
        "print('y_train default rate:', y_train.mean(), '| y_test default rate:', y_test.mean())\n"
    ),
    md("## Step 1 - Compute `digital_footprint_density` (Pre-Imputation)\nThis preserves true digital-data availability before missing values are filled."),
    code(
        "digital_fields = [\n"
        "    'upi_transactions_per_month', 'upi_avg_transaction_amount', 'upi_months_active',\n"
        "    'mobile_wallet_used', 'ecomm_orders_per_month', 'prepaid_orders_ratio'\n"
        "]\n"
        "for split_df in [X_train, X_test]:\n"
        "    split_df['digital_footprint_density'] = split_df[digital_fields].notna().sum(axis=1) / len(digital_fields)\n"
        "\n"
        "print(X_train['digital_footprint_density'].describe())\n"
        "print(X_test['digital_footprint_density'].describe())\n"
    ),
    md("## Step 2 - Missingness Indicator Flags (Pre-Imputation)\nThese binary indicators retain the missingness signal as permanent model features."),
    code(
        "for split_df in [X_train, X_test]:\n"
        "    split_df['upi_data_missing'] = split_df['upi_transactions_per_month'].isna().astype(int)\n"
        "    split_df['rent_data_missing'] = split_df['total_rental_months'].isna().astype(int)\n"
        "    split_df['ecomm_data_missing'] = (\n"
        "        split_df['ecomm_orders_per_month'].isna() | (split_df['ecomm_orders_per_month'] == 0)\n"
        "    ).astype(int)\n"
        "\n"
        "print('Train missing flags counts:')\n"
        "print(X_train[['upi_data_missing', 'rent_data_missing', 'ecomm_data_missing']].sum())\n"
    ),
    md("## Step 3 - Two-Tier Imputation\nApply median imputation for low-missingness fields and borrower-type groupwise median imputation for structured missingness."),
    code(
        "simple_cols = ['same_number_since_year', 'survey_q4', 'survey_q6']\n"
        "simple_imputer = SimpleImputer(strategy='median')\n"
        "X_train[simple_cols] = simple_imputer.fit_transform(X_train[simple_cols])\n"
        "X_test[simple_cols] = simple_imputer.transform(X_test[simple_cols])\n"
        "\n"
        "group_cols = [\n"
        "    'upi_transactions_per_month', 'upi_avg_transaction_amount', 'upi_months_active',\n"
        "    'mobile_wallet_used', 'rent_paid_on_time_months', 'total_rental_months'\n"
        "]\n"
        "group_medians = X_train[group_cols].assign(borrower_type=borrower_type_train).groupby('borrower_type').median(numeric_only=True)\n"
        "global_medians = X_train[group_cols].median(numeric_only=True)\n"
        "\n"
        "def apply_group_imputation(df_in: pd.DataFrame, bt: pd.Series):\n"
        "    out = df_in.copy()\n"
        "    for col in group_cols:\n"
        "        fill_vals = bt.map(group_medians[col]).fillna(global_medians[col])\n"
        "        out[col] = out[col].fillna(fill_vals)\n"
        "    out['ecomm_return_rate'] = out['ecomm_return_rate'].fillna(0.0)\n"
        "    out['prepaid_orders_ratio'] = out['prepaid_orders_ratio'].fillna(0.0)\n"
        "    return out\n"
        "\n"
        "X_train = apply_group_imputation(X_train, borrower_type_train)\n"
        "X_test = apply_group_imputation(X_test, borrower_type_test)\n"
        "\n"
        "if X_train.isna().sum().sum() > 0 or X_test.isna().sum().sum() > 0:\n"
        "    raise ValueError('NaNs remain after imputation. Investigate imputation logic.')\n"
        "\n"
        "print('Remaining NaNs train:', int(X_train.isna().sum().sum()))\n"
        "print('Remaining NaNs test:', int(X_test.isna().sum().sum()))\n"
    ),
    md("## Step 4 - Derived Features\nCreate domain-derived payment, income, telecom, loan and UPI features, then remove redundant raw components."),
    code(
        "INCOME_START = 1\n"
        "INCOME_END = 6\n"
        "INCOME_COLS = [f'income_month_{i}' for i in range(INCOME_START, INCOME_END + 1)]\n"
        "TELECOM_REFERENCE_YEAR = 2024\n"
        "LOAN_STRESS_SENTINEL = 999\n"
        "\n"
        "def add_derived_features(df_in: pd.DataFrame):\n"
        "    out = df_in.copy()\n"
        "    out['utility_payment_ratio'] = np.where(\n"
        "        out['utility_bills_total'] == 0,\n"
        "        0.5,\n"
        "        out['utility_bills_paid'] / out['utility_bills_total']\n"
        "    )\n"
        "    out['rent_consistency_score'] = np.where(\n"
        "        out['rent_data_missing'] == 1,\n"
        "        0.5,\n"
        "        np.where(out['total_rental_months'] == 0, 0.5, out['rent_paid_on_time_months'] / out['total_rental_months'])\n"
        "    )\n"
        "    out['income_mean'] = out[INCOME_COLS].mean(axis=1)\n"
        "    out['income_std'] = out[INCOME_COLS].std(axis=1)\n"
        "    out['income_regularity_index'] = np.where(\n"
        "        out['income_mean'] == 0,\n"
        "        0,\n"
        "        1 - (out['income_std'] / out['income_mean'])\n"
        "    )\n"
        "    out['income_regularity_index'] = out['income_regularity_index'].clip(0, 1)\n"
        "    out['income_trend'] = out['income_month_6'] - out['income_month_1']\n"
        "    out['telecom_stability_years'] = TELECOM_REFERENCE_YEAR - out['same_number_since_year']\n"
        "    denom = out['income_mean'] * out['loan_tenure_months']\n"
        "    out['loan_to_income_ratio'] = np.where(denom == 0, LOAN_STRESS_SENTINEL, out['loan_amount_requested'] / denom)\n"
        "    out['upi_consistency_score'] = (out['upi_transactions_per_month'] / 120.0) * (out['upi_months_active'] / 36.0)\n"
        "    out = out.drop(columns=INCOME_COLS + ['same_number_since_year', 'upi_transactions_per_month', 'upi_months_active'])\n"
        "    return out\n"
        "\n"
        "X_train = add_derived_features(X_train)\n"
        "X_test = add_derived_features(X_test)\n"
        "print('Post-derived train shape:', X_train.shape)\n"
        "print(X_train[['utility_payment_ratio', 'income_mean', 'upi_consistency_score']].head())\n"
    ),
    md("## Step 5 - Psychometric Composite Scores\nBuild composite psychometric factors with reverse-scoring for Q3 and Q7, then remove the original survey questions."),
    code(
        "survey_cols = [f'survey_q{i}' for i in range(1, 9)]\n"
        "\n"
        "def add_psych_composites(df_in: pd.DataFrame):\n"
        "    out = df_in.copy()\n"
        "    q3_rev = 6 - out['survey_q3']\n"
        "    q7_rev = 6 - out['survey_q7']\n"
        "    out['financial_discipline_score'] = pd.concat([out['survey_q1'], out['survey_q2'], q3_rev, out['survey_q4'], out['survey_q8']], axis=1).mean(axis=1)\n"
        "    out['future_planning_score'] = pd.concat([out['survey_q5'], out['survey_q6']], axis=1).mean(axis=1)\n"
        "    out['risk_appetite_score'] = pd.concat([q3_rev, q7_rev], axis=1).mean(axis=1)\n"
        "    out = out.drop(columns=survey_cols)\n"
        "    return out\n"
        "\n"
        "X_train = add_psych_composites(X_train)\n"
        "X_test = add_psych_composites(X_test)\n"
        "print(X_train[['financial_discipline_score', 'future_planning_score', 'risk_appetite_score']].describe())\n"
    ),
    md("## Step 6 - State to Region Mapping and One-Hot Encoding\nMap states to regions, then one-hot encode required categorical variables using train-fitted encoder."),
    code(
        "state_to_region = {\n"
        "    'Delhi': 'North', 'Uttar Pradesh': 'North', 'Rajasthan': 'North',\n"
        "    'Karnataka': 'South', 'Tamil Nadu': 'South', 'Telangana': 'South',\n"
        "    'Maharashtra': 'West', 'Gujarat': 'West',\n"
        "    'Bihar': 'East', 'Odisha': 'East',\n"
        "    'Madhya Pradesh': 'Central'\n"
        "}\n"
        "for split_df in [X_train, X_test]:\n"
        "    split_df['region'] = split_df['state'].map(state_to_region).fillna('Other')\n"
        "\n"
        "identifier_cols = [c for c in ['borrower_id'] if c in X_train.columns]\n"
        "if identifier_cols:\n"
        "    print('Dropping identifier columns from model features:', identifier_cols)\n"
        "\n"
        "categorical_cols = ['region', 'borrower_type', 'employment_type', 'loan_purpose']\n"
        "ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')\n"
        "train_cat = ohe.fit_transform(X_train[categorical_cols])\n"
        "test_cat = ohe.transform(X_test[categorical_cols])\n"
        "encoded_cols = ohe.get_feature_names_out(categorical_cols)\n"
        "\n"
        "X_train = pd.concat([\n"
        "    X_train.drop(columns=categorical_cols + ['state'] + identifier_cols).reset_index(drop=True),\n"
        "    pd.DataFrame(train_cat, columns=encoded_cols)\n"
        "], axis=1)\n"
        "X_test = pd.concat([\n"
        "    X_test.drop(columns=categorical_cols + ['state'] + identifier_cols).reset_index(drop=True),\n"
        "    pd.DataFrame(test_cat, columns=encoded_cols)\n"
        "], axis=1)\n"
        "\n"
        "X_train.index = y_train.index\n"
        "X_test.index = y_test.index\n"
        "print('Encoded columns count:', len(encoded_cols))\n"
        "print('Train shape after encoding:', X_train.shape)\n"
    ),
    md("## Step 7 - Discretization\nCreate train-derived quantile bins for loan amount and income level, then ordinal-encode and keep both raw and binned features."),
    code(
        "loan_labels = ['Small', 'Medium', 'Large', 'Very_Large']\n"
        "income_labels = ['Low', 'Medium', 'High']\n"
        "loan_codes = {label: idx for idx, label in enumerate(loan_labels)}\n"
        "income_codes = {label: idx for idx, label in enumerate(income_labels)}\n"
        "\n"
        "_, loan_bins = pd.qcut(X_train['loan_amount_requested'], q=4, labels=loan_labels, retbins=True, duplicates='drop')\n"
        "_, income_bins = pd.qcut(X_train['income_mean'], q=3, labels=income_labels, retbins=True, duplicates='drop')\n"
        "loan_bins[0] = -np.inf\n"
        "loan_bins[-1] = np.inf\n"
        "income_bins[0] = -np.inf\n"
        "income_bins[-1] = np.inf\n"
        "\n"
        "X_train['loan_amount_bin'] = pd.cut(X_train['loan_amount_requested'], bins=loan_bins, labels=loan_labels, include_lowest=True).map(loan_codes).astype(int)\n"
        "X_test['loan_amount_bin'] = pd.cut(X_test['loan_amount_requested'], bins=loan_bins, labels=loan_labels, include_lowest=True).map(loan_codes).astype(int)\n"
        "X_train['income_level_bin'] = pd.cut(X_train['income_mean'], bins=income_bins, labels=income_labels, include_lowest=True).map(income_codes).astype(int)\n"
        "X_test['income_level_bin'] = pd.cut(X_test['income_mean'], bins=income_bins, labels=income_labels, include_lowest=True).map(income_codes).astype(int)\n"
        "\n"
        "print(X_train[['loan_amount_bin', 'income_level_bin']].describe())\n"
    ),
    md("## Step 8 - Normalization\nScale only continuous columns using train-fitted MinMaxScaler while leaving one-hot, ordinal bins, and missingness flags unchanged."),
    code(
        "flag_cols = ['upi_data_missing', 'rent_data_missing', 'ecomm_data_missing']\n"
        "ordinal_cols = ['loan_amount_bin', 'income_level_bin']\n"
        "binary_ohe_cols = [c for c in X_train.columns if set(pd.Series(X_train[c]).dropna().unique()).issubset({0, 1}) and c not in ordinal_cols + flag_cols]\n"
        "exclude_cols = set(flag_cols + ordinal_cols + binary_ohe_cols)\n"
        "numeric_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()\n"
        "continuous_cols = [c for c in numeric_cols if c not in exclude_cols]\n"
        "non_numeric_cols = [c for c in X_train.columns if c not in numeric_cols]\n"
        "print('Non-numeric columns excluded from scaling:', non_numeric_cols)\n"
        "\n"
        "scaler = MinMaxScaler()\n"
        "X_train[continuous_cols] = scaler.fit_transform(X_train[continuous_cols])\n"
        "X_test[continuous_cols] = scaler.transform(X_test[continuous_cols])\n"
        "\n"
        "train_min, train_max = X_train[continuous_cols].min().min(), X_train[continuous_cols].max().max()\n"
        "print('Scaled continuous min/max (train):', train_min, train_max)\n"
        "if train_min < -1e-8 or train_max > 1 + 1e-8:\n"
        "    raise ValueError('Scaling bounds violation detected.')\n"
    ),
    md("## Step 9 - Exploratory PCA\nFit PCA on engineered training features, produce scree plot, and report components needed to explain 85% variance."),
    code(
        "pca = PCA()\n"
        "pca.fit(X_train)\n"
        "cum_exp = np.cumsum(pca.explained_variance_ratio_)\n"
        "target_var = 0.85\n"
        "n_comp_85 = int(np.argmax(cum_exp >= target_var) + 1)\n"
        "\n"
        "plt.figure(figsize=(10, 6))\n"
        "plt.plot(range(1, len(cum_exp) + 1), cum_exp, marker='o', label='Cumulative Explained Variance')\n"
        "plt.axhline(target_var, color='red', linestyle='--', label='85% Variance Threshold')\n"
        "plt.axvline(n_comp_85, color='green', linestyle='--', label=f'Components = {n_comp_85}')\n"
        "plt.title('Stage 1 Scree Plot - Cumulative Explained Variance')\n"
        "plt.xlabel('Number of Components')\n"
        "plt.ylabel('Cumulative Explained Variance Ratio')\n"
        "plt.legend()\n"
        "save_plot('stage1_scree_plot')\n"
        "plt.show()\n"
        "print('Components to explain 85% variance:', n_comp_85)\n"
    ),
    md("## Save Stage 1 Outputs\nPersist engineered matrices, targets, and retained side variables for downstream stages."),
    code(
        "stage1_output = {\n"
        "    'X_train_eng': X_train,\n"
        "    'X_test_eng': X_test,\n"
        "    'y_train': y_train,\n"
        "    'y_test': y_test,\n"
        "    'borrower_type_train': borrower_type_train,\n"
        "    'borrower_type_test': borrower_type_test,\n"
        "    'default_probability_test': dp_test,\n"
        "    'n_comp_85': n_comp_85,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage1_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage1_output, f)\n"
        "print('Saved:', out_path)\n"
        "print('Output shapes:', X_train.shape, X_test.shape)\n"
    ),
    md("## Stage 1 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 1 SUMMARY')\n"
        "print('- Completed preliminary split and full feature engineering pipeline.')\n"
        "print(f\"- Saved engineered train/test matrices to: {out_path}\")\n"
        "print(f\"- X_train_eng shape: {X_train.shape}\")\n"
        "print(f\"- X_test_eng shape: {X_test.shape}\")\n"
        "print(f\"- Train default rate: {y_train.mean():.4f}\")\n"
        "print(f\"- Test default rate: {y_test.mean():.4f}\")\n"
        "print(f\"- PCA components for 85% variance: {n_comp_85}\")\n"
        "print('=' * 70)\n"
    ),
]


stage2_cells = [
    md("# Stage 2 - Unsupervised Clustering\nThis notebook follows the exact Stage 2 clustering workflow and appends `cluster_id` to engineered feature matrices."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from sklearn.cluster import KMeans\n"
        "from sklearn.metrics import silhouette_score\n"
        "from sklearn.mixture import GaussianMixture\n"
        "\n"
        "RANDOM_STATE = 42\n"
        "BASE_DIR = Path.cwd().parent\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
        "PLOT_DIR = BASE_DIR / 'outputs' / 'plots' / 'stage2'\n"
        "PLOT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "def save_plot(name: str):\n"
        "    path = PLOT_DIR / f'{name}.png'\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(path, dpi=300, bbox_inches='tight')\n"
        "    print(f'Saved plot: {path}')\n"
    ),
    md("## Load Stage 1 Outputs\nLoad engineered train/test matrices and targets from disk."),
    code(
        "with open(PROCESSED_DIR / 'stage1_outputs.pkl', 'rb') as f:\n"
        "    stage1 = pickle.load(f)\n"
        "X_train_eng = stage1['X_train_eng'].copy()\n"
        "X_test_eng = stage1['X_test_eng'].copy()\n"
        "y_train = stage1['y_train'].copy()\n"
        "borrower_type_train = stage1['borrower_type_train'].copy()\n"
        "print('Loaded shapes:', X_train_eng.shape, X_test_eng.shape)\n"
    ),
    md("## Step 1 - Select Clustering Features\nUse only the mandated 8 behavioral composite features for clustering."),
    code(
        "clustering_features = [\n"
        "    'utility_payment_ratio', 'rent_consistency_score', 'income_regularity_index',\n"
        "    'upi_consistency_score', 'digital_footprint_density', 'financial_discipline_score',\n"
        "    'future_planning_score', 'risk_appetite_score'\n"
        "]\n"
        "X_train_clust = X_train_eng[clustering_features].copy()\n"
        "X_test_clust = X_test_eng[clustering_features].copy()\n"
        "print('Clustering matrix shapes:', X_train_clust.shape, X_test_clust.shape)\n"
        "print(X_train_clust.describe().T[['mean', 'std']])\n"
    ),
    md("## Step 2 - Determine Optimal K\nEvaluate K=2..10 using inertia and silhouette score, then choose K with highest silhouette (tie -> lower K)."),
    code(
        "k_values = list(range(2, 11))\n"
        "inertia_scores = []\n"
        "sil_scores = []\n"
        "for k in k_values:\n"
        "    km = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE)\n"
        "    labels = km.fit_predict(X_train_clust)\n"
        "    inertia_scores.append(km.inertia_)\n"
        "    sil_scores.append(silhouette_score(X_train_clust, labels))\n"
        "\n"
        "optimal_k = int(pd.Series(sil_scores, index=k_values).sort_values(ascending=False).index[0])\n"
        "print('K vs silhouette:', dict(zip(k_values, np.round(sil_scores, 4))))\n"
        "print('Selected optimal K:', optimal_k)\n"
        "\n"
        "plt.figure(figsize=(10, 6))\n"
        "plt.plot(k_values, inertia_scores, marker='o', label='Inertia')\n"
        "plt.title('Stage 2 Elbow Curve')\n"
        "plt.xlabel('Number of Clusters (K)')\n"
        "plt.ylabel('Inertia')\n"
        "plt.legend()\n"
        "save_plot('stage2_elbow_curve')\n"
        "plt.show()\n"
        "\n"
        "plt.figure(figsize=(10, 6))\n"
        "plt.plot(k_values, sil_scores, marker='o', label='Silhouette Score')\n"
        "plt.title('Stage 2 Silhouette Score by K')\n"
        "plt.xlabel('Number of Clusters (K)')\n"
        "plt.ylabel('Silhouette Score')\n"
        "plt.legend()\n"
        "save_plot('stage2_silhouette_curve')\n"
        "plt.show()\n"
    ),
    md("## Step 3 and Step 4 - Fit KMeans and GMM, Compare Silhouette\nTrain both models at optimal K and keep the one with better silhouette score."),
    code(
        "kmeans_model = KMeans(n_clusters=optimal_k, n_init=10, random_state=RANDOM_STATE)\n"
        "kmeans_labels = kmeans_model.fit_predict(X_train_clust)\n"
        "kmeans_sil = silhouette_score(X_train_clust, kmeans_labels)\n"
        "\n"
        "gmm_model = GaussianMixture(n_components=optimal_k, random_state=RANDOM_STATE)\n"
        "gmm_model.fit(X_train_clust)\n"
        "gmm_labels = gmm_model.predict(X_train_clust)\n"
        "gmm_sil = silhouette_score(X_train_clust, gmm_labels)\n"
        "\n"
        "if kmeans_sil >= gmm_sil:\n"
        "    cluster_model = kmeans_model\n"
        "    model_name = 'KMeans'\n"
        "else:\n"
        "    cluster_model = gmm_model\n"
        "    model_name = 'GMM'\n"
        "print(f'KMeans silhouette: {kmeans_sil:.4f} | GMM silhouette: {gmm_sil:.4f}')\n"
        "print('Selected cluster model:', model_name)\n"
    ),
    md("## Step 5 - Cluster Profiling\nCompute per-cluster means of all clustering features and default rate, then assign descriptive profile names."),
    code(
        "cluster_train_labels = cluster_model.predict(X_train_clust)\n"
        "profile_df = X_train_clust.copy()\n"
        "profile_df['cluster_id'] = cluster_train_labels\n"
        "profile_df['defaulted'] = y_train.values\n"
        "cluster_profile_table = profile_df.groupby('cluster_id').mean(numeric_only=True)\n"
        "\n"
        "cluster_names = {}\n"
        "for cid, row in cluster_profile_table.iterrows():\n"
        "    if row['digital_footprint_density'] > cluster_profile_table['digital_footprint_density'].median() and row['financial_discipline_score'] > cluster_profile_table['financial_discipline_score'].median():\n"
        "        cluster_names[cid] = 'Digitally Active Disciplined'\n"
        "    elif row['utility_payment_ratio'] > cluster_profile_table['utility_payment_ratio'].median() and row['rent_consistency_score'] > cluster_profile_table['rent_consistency_score'].median():\n"
        "        cluster_names[cid] = 'Cash-Based Reliable'\n"
        "    else:\n"
        "        cluster_names[cid] = 'High-Risk Sparse Data'\n"
        "\n"
        "cluster_profile_table['cluster_profile_name'] = pd.Series(cluster_names)\n"
        "print(cluster_profile_table)\n"
    ),
    md("## Step 6 - Cross-Borrower-Type Check\nCheck borrower-type concentration per cluster and flag clusters where a single type exceeds 75%."),
    code(
        "cross_df = pd.DataFrame({'cluster_id': cluster_train_labels, 'borrower_type': borrower_type_train.values})\n"
        "cross_tab = pd.crosstab(cross_df['cluster_id'], cross_df['borrower_type'], normalize='index')\n"
        "print(cross_tab)\n"
        "for cid in cross_tab.index:\n"
        "    top_ratio = cross_tab.loc[cid].max()\n"
        "    top_type = cross_tab.loc[cid].idxmax()\n"
        "    if top_ratio > 0.75:\n"
        "        print(f'WARNING: Cluster {cid} is {top_ratio:.2%} {top_type} (>75%).')\n"
    ),
    md("## Step 7 - Assign Cluster Labels\nPredict cluster IDs for both train and test sets and add `cluster_id` as an ordinal integer feature."),
    code(
        "cluster_train_labels = cluster_model.predict(X_train_clust)\n"
        "cluster_test_labels = cluster_model.predict(X_test_clust)\n"
        "X_train_eng['cluster_id'] = cluster_train_labels.astype(int)\n"
        "X_test_eng['cluster_id'] = cluster_test_labels.astype(int)\n"
        "print(X_train_eng['cluster_id'].value_counts().sort_index())\n"
        "print(X_test_eng['cluster_id'].value_counts().sort_index())\n"
    ),
    md("## Save Stage 2 Outputs"),
    code(
        "stage2_output = {\n"
        "    **stage1,\n"
        "    'X_train_eng': X_train_eng,\n"
        "    'X_test_eng': X_test_eng,\n"
        "    'cluster_model': cluster_model,\n"
        "    'cluster_profile_table': cluster_profile_table,\n"
        "    'cluster_names': cluster_names,\n"
        "    'clustering_features': clustering_features,\n"
        "    'optimal_k': optimal_k,\n"
        "    'kmeans_silhouette': kmeans_sil,\n"
        "    'gmm_silhouette': gmm_sil,\n"
        "    'selected_cluster_model_name': model_name,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage2_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage2_output, f)\n"
        "print('Saved:', out_path)\n"
    ),
    md("## Stage 2 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 2 SUMMARY')\n"
        "print('- Completed feature-restricted unsupervised clustering and model comparison.')\n"
        "print(f\"- Optimal K: {optimal_k}\")\n"
        "print(f\"- KMeans silhouette: {kmeans_sil:.4f}\")\n"
        "print(f\"- GMM silhouette: {gmm_sil:.4f}\")\n"
        "print(f\"- Selected cluster model: {model_name}\")\n"
        "print(f\"- Added cluster_id to X_train_eng and X_test_eng\")\n"
        "print(f\"- Saved outputs to: {out_path}\")\n"
        "print('=' * 70)\n"
    ),
]


stage3_cells = [
    md("# Stage 3 - Model Training\nThis notebook implements the exact SMOTE placement, CV strategy, tuning grids, and final model fitting rules from the pipeline."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from sklearn.model_selection import StratifiedKFold, cross_validate, StratifiedShuffleSplit, ParameterGrid\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.naive_bayes import GaussianNB\n"
        "from sklearn.neighbors import KNeighborsClassifier\n"
        "from sklearn.tree import DecisionTreeClassifier\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.svm import SVC\n"
        "from sklearn.metrics import roc_auc_score\n"
        "from imblearn.over_sampling import SMOTE\n"
        "from imblearn.pipeline import Pipeline as ImbPipeline\n"
        "from xgboost import XGBClassifier\n"
        "\n"
        "RANDOM_STATE = 42\n"
        "BASE_DIR = Path.cwd().parent\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
        "PLOT_DIR = BASE_DIR / 'outputs' / 'plots' / 'stage3'\n"
        "MODEL_DIR = BASE_DIR / 'models'\n"
        "PLOT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "MODEL_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "def save_plot(name: str):\n"
        "    path = PLOT_DIR / f'{name}.png'\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(path, dpi=300, bbox_inches='tight')\n"
        "    print(f'Saved plot: {path}')\n"
    ),
    md("## Load Stage 2 Outputs"),
    code(
        "with open(PROCESSED_DIR / 'stage2_outputs.pkl', 'rb') as f:\n"
        "    stage2 = pickle.load(f)\n"
        "X_train_eng = stage2['X_train_eng']\n"
        "X_test_eng = stage2['X_test_eng']\n"
        "y_train = stage2['y_train']\n"
        "y_test = stage2['y_test']\n"
        "print('Train/Test shapes:', X_train_eng.shape, X_test_eng.shape)\n"
        "print('Class distribution train:', y_train.value_counts(normalize=True))\n"
    ),
    md("## CV and SMOTE Setup\nDefine shared fold object and scoring metrics. SMOTE is applied inside CV folds via `ImbPipeline`."),
    code(
        "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)\n"
        "scoring_metrics = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']\n"
        "\n"
        "def evaluate_cv(model):\n"
        "    pipe = ImbPipeline([('smote', SMOTE(random_state=RANDOM_STATE)), ('classifier', model)])\n"
        "    return cross_validate(pipe, X_train_eng, y_train, cv=cv, scoring=scoring_metrics, n_jobs=-1, return_train_score=False)\n"
        "\n"
        "def tune_grid(model_factory, param_grid):\n"
        "    rows = []\n"
        "    for params in ParameterGrid(param_grid):\n"
        "        model = model_factory(**params)\n"
        "        cv_result = evaluate_cv(model)\n"
        "        rows.append({\n"
        "            'params': params,\n"
        "            'mean_roc_auc': float(np.mean(cv_result['test_roc_auc'])),\n"
        "            'std_roc_auc': float(np.std(cv_result['test_roc_auc'])),\n"
        "            'cv_result': cv_result\n"
        "        })\n"
        "    tuning_df = pd.DataFrame(rows).sort_values('mean_roc_auc', ascending=False).reset_index(drop=True)\n"
        "    return tuning_df\n"
    ),
    md("## Model 1 - Logistic Regression (L2)\nTune C by CV ROC-AUC, then fit final model on full SMOTE-resampled training set."),
    code(
        "c_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}\n"
        "l2_tuning = tune_grid(lambda C: LogisticRegression(C=C, penalty='l2', solver='lbfgs', max_iter=1000, random_state=RANDOM_STATE), c_grid)\n"
        "best_c_l2 = l2_tuning.loc[0, 'params']['C']\n"
        "print('Best C (L2):', best_c_l2)\n"
        "\n"
        "smote = SMOTE(random_state=RANDOM_STATE)\n"
        "X_train_sm, y_train_sm = smote.fit_resample(X_train_eng, y_train)\n"
        "lr_l2 = LogisticRegression(C=best_c_l2, penalty='l2', solver='lbfgs', max_iter=1000, random_state=RANDOM_STATE)\n"
        "lr_l2.fit(X_train_sm, y_train_sm)\n"
        "\n"
        "coef_abs = pd.Series(np.abs(lr_l2.coef_[0]), index=X_train_eng.columns).sort_values(ascending=False).head(15)\n"
        "plt.figure(figsize=(10, 6))\n"
        "sns.barplot(x=coef_abs.values, y=coef_abs.index, label='|Coefficient|')\n"
        "plt.title('Top 15 Logistic Regression L2 Coefficients')\n"
        "plt.xlabel('Absolute Coefficient Magnitude')\n"
        "plt.ylabel('Feature')\n"
        "plt.legend()\n"
        "save_plot('stage3_lr_l2_top15_coefficients')\n"
        "plt.show()\n"
        "print(coef_abs)\n"
    ),
    md("## Model 2 - Logistic Regression (L1)\nTune C, fit final model, and report sparsity (number of zero coefficients)."),
    code(
        "l1_tuning = tune_grid(lambda C: LogisticRegression(C=C, penalty='l1', solver='liblinear', max_iter=1000, random_state=RANDOM_STATE), c_grid)\n"
        "best_c_l1 = l1_tuning.loc[0, 'params']['C']\n"
        "print('Best C (L1):', best_c_l1)\n"
        "lr_l1 = LogisticRegression(C=best_c_l1, penalty='l1', solver='liblinear', max_iter=1000, random_state=RANDOM_STATE)\n"
        "lr_l1.fit(X_train_sm, y_train_sm)\n"
        "l1_zero_count = int(np.sum(lr_l1.coef_[0] == 0))\n"
        "l2_zero_count = int(np.sum(lr_l2.coef_[0] == 0))\n"
        "print('L1 zero coefficients:', l1_zero_count)\n"
        "print('L2 zero coefficients:', l2_zero_count)\n"
    ),
    md("## Model 3 - Naive Bayes\nTrain GaussianNB with fold-wise SMOTE in CV and final fit on SMOTE-resampled full training data."),
    code(
        "nb_cv = evaluate_cv(GaussianNB())\n"
        "nb_model = GaussianNB()\n"
        "nb_model.fit(X_train_sm, y_train_sm)\n"
        "print('Naive Bayes CV ROC-AUC mean:', np.mean(nb_cv['test_roc_auc']))\n"
        "print('Note: Feature independence assumption is likely violated for this dataset.')\n"
    ),
    md("## Model 4 - KNN\nTune n_neighbors, fit final KNN, and note scale sensitivity plus dimensionality constraints."),
    code(
        "knn_tuning = tune_grid(lambda n_neighbors: KNeighborsClassifier(n_neighbors=n_neighbors, metric='minkowski'), {'n_neighbors': [3, 5, 7, 9, 11, 15, 21]})\n"
        "best_k_knn = knn_tuning.loc[0, 'params']['n_neighbors']\n"
        "knn_model = KNeighborsClassifier(n_neighbors=best_k_knn, metric='minkowski')\n"
        "knn_model.fit(X_train_sm, y_train_sm)\n"
        "print('Best K (KNN):', best_k_knn)\n"
        "print('Normalization from Stage 1 already applied. High dimensionality may still dilute neighborhood distance quality.')\n"
    ),
    md("## Model 5 - Decision Tree (Overfit and Tuned)\nFit an overfit baseline and a tuned variant; keep tuned variant for Stage 4 main evaluation."),
    code(
        "dt_overfit = DecisionTreeClassifier(criterion='gini', max_depth=None, random_state=RANDOM_STATE)\n"
        "dt_overfit.fit(X_train_sm, y_train_sm)\n"
        "train_acc_overfit = dt_overfit.score(X_train_sm, y_train_sm)\n"
        "test_acc_overfit = dt_overfit.score(X_test_eng, y_test)\n"
        "print('DT-overfit train accuracy:', train_acc_overfit)\n"
        "print('DT-overfit test accuracy:', test_acc_overfit)\n"
        "\n"
        "dt_tuning = tune_grid(\n"
        "    lambda max_depth, criterion: DecisionTreeClassifier(max_depth=max_depth, criterion=criterion, random_state=RANDOM_STATE),\n"
        "    {'max_depth': [3, 5, 7, 10, 15], 'criterion': ['gini', 'entropy']}\n"
        ")\n"
        "best_dt_params = dt_tuning.loc[0, 'params']\n"
        "dt_tuned = DecisionTreeClassifier(**best_dt_params, random_state=RANDOM_STATE)\n"
        "dt_tuned.fit(X_train_sm, y_train_sm)\n"
        "print('Best DT params:', best_dt_params)\n"
    ),
    md("## Model 6 - Random Forest\nTune and fit final random forest on full SMOTE training set."),
    code(
        "rf_tuning = tune_grid(\n"
        "    lambda n_estimators, max_depth, min_samples_split: RandomForestClassifier(\n"
        "        n_estimators=n_estimators, max_depth=max_depth, min_samples_split=min_samples_split, random_state=RANDOM_STATE, n_jobs=-1\n"
        "    ),\n"
        "    {'n_estimators': [100, 200, 300], 'max_depth': [10, 20, None], 'min_samples_split': [2, 5]}\n"
        ")\n"
        "best_rf_params = rf_tuning.loc[0, 'params']\n"
        "rf_model = RandomForestClassifier(**best_rf_params, random_state=RANDOM_STATE, n_jobs=-1)\n"
        "rf_model.fit(X_train_sm, y_train_sm)\n"
        "print('Best RF params:', best_rf_params)\n"
    ),
    md("## Model 7 - XGBoost\nTune and fit final XGBoost model using specified hyperparameter search space."),
    code(
        "xgb_tuning = tune_grid(\n"
        "    lambda n_estimators, max_depth, learning_rate, subsample: XGBClassifier(\n"
        "        n_estimators=n_estimators, max_depth=max_depth, learning_rate=learning_rate, subsample=subsample,\n"
        "        use_label_encoder=False, eval_metric='logloss', random_state=RANDOM_STATE\n"
        "    ),\n"
        "    {'n_estimators': [100, 200, 300], 'max_depth': [3, 5, 7], 'learning_rate': [0.01, 0.1, 0.2], 'subsample': [0.8, 1.0]}\n"
        ")\n"
        "best_xgb_params = xgb_tuning.loc[0, 'params']\n"
        "xgb_model = XGBClassifier(**best_xgb_params, use_label_encoder=False, eval_metric='logloss', random_state=RANDOM_STATE)\n"
        "xgb_model.fit(X_train_sm, y_train_sm)\n"
        "print('Best XGB params:', best_xgb_params)\n"
    ),
    md("## Model 8 - SVM\nTrain on a stratified 3000-row subsample of SMOTE-resampled training data and tune C/kernel."),
    code(
        "svm_sample_size = 3000\n"
        "sss = StratifiedShuffleSplit(n_splits=1, train_size=svm_sample_size, random_state=RANDOM_STATE)\n"
        "svm_idx, _ = next(sss.split(X_train_sm, y_train_sm))\n"
        "X_svm = X_train_sm.iloc[svm_idx]\n"
        "y_svm = y_train_sm.iloc[svm_idx]\n"
        "print('SVM sample shape:', X_svm.shape)\n"
        "\n"
        "svm_rows = []\n"
        "for params in ParameterGrid({'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']}):\n"
        "    svm = SVC(C=params['C'], kernel=params['kernel'], probability=True, random_state=RANDOM_STATE)\n"
        "    cv_result = cross_validate(svm, X_svm, y_svm, cv=cv, scoring=scoring_metrics, n_jobs=-1)\n"
        "    svm_rows.append({'params': params, 'mean_roc_auc': float(np.mean(cv_result['test_roc_auc'])), 'cv_result': cv_result})\n"
        "svm_tuning = pd.DataFrame(svm_rows).sort_values('mean_roc_auc', ascending=False).reset_index(drop=True)\n"
        "best_svm_params = svm_tuning.loc[0, 'params']\n"
        "svm_model = SVC(C=best_svm_params['C'], kernel=best_svm_params['kernel'], probability=True, random_state=RANDOM_STATE)\n"
        "svm_model.fit(X_svm, y_svm)\n"
        "print('Best SVM params:', best_svm_params)\n"
    ),
    md("## Build CV Summary Table\nAggregate mean and std metrics for all models from fold-wise CV results."),
    code(
        "cv_results_map = {\n"
        "    'LR_L2': l2_tuning.loc[0, 'cv_result'],\n"
        "    'LR_L1': l1_tuning.loc[0, 'cv_result'],\n"
        "    'NaiveBayes': nb_cv,\n"
        "    'KNN': knn_tuning.loc[0, 'cv_result'],\n"
        "    'DecisionTree_Tuned': dt_tuning.loc[0, 'cv_result'],\n"
        "    'RandomForest': rf_tuning.loc[0, 'cv_result'],\n"
        "    'XGBoost': xgb_tuning.loc[0, 'cv_result'],\n"
        "    'SVM': svm_tuning.loc[0, 'cv_result'],\n"
        "}\n"
        "\n"
        "rows = []\n"
        "for model_name, result in cv_results_map.items():\n"
        "    rows.append({\n"
        "        'model': model_name,\n"
        "        'accuracy_mean': np.mean(result['test_accuracy']), 'accuracy_std': np.std(result['test_accuracy']),\n"
        "        'precision_mean': np.mean(result['test_precision']), 'precision_std': np.std(result['test_precision']),\n"
        "        'recall_mean': np.mean(result['test_recall']), 'recall_std': np.std(result['test_recall']),\n"
        "        'f1_mean': np.mean(result['test_f1']), 'f1_std': np.std(result['test_f1']),\n"
        "        'roc_auc_mean': np.mean(result['test_roc_auc']), 'roc_auc_std': np.std(result['test_roc_auc']),\n"
        "    })\n"
        "cv_summary = pd.DataFrame(rows).sort_values('roc_auc_mean', ascending=False)\n"
        "print(cv_summary)\n"
    ),
    md("## Save Stage 3 Outputs\nPersist all trained models, CV summary, and best hyperparameters."),
    code(
        "models = {\n"
        "    'lr_l2': lr_l2,\n"
        "    'lr_l1': lr_l1,\n"
        "    'naive_bayes': nb_model,\n"
        "    'knn': knn_model,\n"
        "    'decision_tree_overfit': dt_overfit,\n"
        "    'decision_tree_tuned': dt_tuned,\n"
        "    'random_forest': rf_model,\n"
        "    'xgboost': xgb_model,\n"
        "    'svm': svm_model,\n"
        "}\n"
        "for name, model in models.items():\n"
        "    with open(MODEL_DIR / f'{name}.pkl', 'wb') as f:\n"
        "        pickle.dump(model, f)\n"
        "\n"
        "stage3_output = {\n"
        "    **stage2,\n"
        "    'models': models,\n"
        "    'cv_summary': cv_summary,\n"
        "    'best_params': {\n"
        "        'lr_l2': {'C': best_c_l2},\n"
        "        'lr_l1': {'C': best_c_l1},\n"
        "        'knn': {'n_neighbors': best_k_knn},\n"
        "        'decision_tree_tuned': best_dt_params,\n"
        "        'random_forest': best_rf_params,\n"
        "        'xgboost': best_xgb_params,\n"
        "        'svm': best_svm_params,\n"
        "    },\n"
        "    'dt_overfit_train_acc': train_acc_overfit,\n"
        "    'dt_overfit_test_acc': test_acc_overfit,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage3_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage3_output, f)\n"
        "print('Saved:', out_path)\n"
    ),
    md("## Stage 3 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 3 SUMMARY')\n"
        "print('- Trained and stored all required models with proper SMOTE placement.')\n"
        "print(f\"- CV table rows: {cv_summary.shape[0]}\")\n"
        "print(f\"- Best CV ROC-AUC model: {cv_summary.iloc[0]['model']}\")\n"
        "print(f\"- DT overfit train/test accuracy: {train_acc_overfit:.4f} / {test_acc_overfit:.4f}\")\n"
        "print(f\"- Saved outputs to: {out_path}\")\n"
        "print('=' * 70)\n"
    ),
]


stage4_cells = [
    md("# Stage 4 - Model Evaluation\nThis notebook evaluates trained models on the untouched test set and selects `best_model` with explicit threshold analysis and calibration checks."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from sklearn.metrics import (\n"
        "    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,\n"
        "    average_precision_score, brier_score_loss, confusion_matrix,\n"
        "    precision_recall_curve, roc_curve\n"
        ")\n"
        "from sklearn.calibration import calibration_curve, CalibratedClassifierCV\n"
        "\n"
        "BASE_DIR = Path.cwd().parent\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
        "PLOT_DIR = BASE_DIR / 'outputs' / 'plots' / 'stage4'\n"
        "PLOT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "def save_plot(name: str):\n"
        "    path = PLOT_DIR / f'{name}.png'\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(path, dpi=300, bbox_inches='tight')\n"
        "    print(f'Saved plot: {path}')\n"
    ),
    md("## Load Stage 3 Outputs"),
    code(
        "with open(PROCESSED_DIR / 'stage3_outputs.pkl', 'rb') as f:\n"
        "    stage3 = pickle.load(f)\n"
        "X_test_eng = stage3['X_test_eng']\n"
        "X_train_eng = stage3['X_train_eng']\n"
        "y_test = stage3['y_test']\n"
        "y_train = stage3['y_train']\n"
        "models = stage3['models']\n"
        "borrower_type_test = stage3['borrower_type_test']\n"
        "default_probability_test = stage3['default_probability_test']\n"
        "cv_summary = stage3['cv_summary']\n"
        "print('Loaded test shape:', X_test_eng.shape)\n"
        "print('Models:', list(models.keys()))\n"
    ),
    md("## Step 1 - Per-Model Metrics\nCompute predictions, probabilities, classification metrics, ROC/PR metrics, Brier score, and confusion matrices."),
    code(
        "model_eval = {}\n"
        "for name, model in models.items():\n"
        "    if name == 'decision_tree_overfit':\n"
        "        continue\n"
        "    y_pred = model.predict(X_test_eng)\n"
        "    y_prob = model.predict_proba(X_test_eng)[:, 1]\n"
        "    cm = confusion_matrix(y_test, y_pred)\n"
        "    model_eval[name] = {\n"
        "        'y_pred': y_pred,\n"
        "        'y_prob': y_prob,\n"
        "        'accuracy': accuracy_score(y_test, y_pred),\n"
        "        'precision': precision_score(y_test, y_pred, zero_division=0),\n"
        "        'recall': recall_score(y_test, y_pred, zero_division=0),\n"
        "        'f1': f1_score(y_test, y_pred, zero_division=0),\n"
        "        'roc_auc': roc_auc_score(y_test, y_prob),\n"
        "        'avg_precision': average_precision_score(y_test, y_prob),\n"
        "        'brier': brier_score_loss(y_test, y_prob),\n"
        "        'confusion_matrix': cm,\n"
        "    }\n"
        "eval_table = pd.DataFrame({k: {m: v[m] for m in ['accuracy', 'precision', 'recall', 'f1', 'roc_auc', 'avg_precision', 'brier']} for k, v in model_eval.items()}).T\n"
        "print(eval_table.sort_values('roc_auc', ascending=False))\n"
    ),
    md("## Step 2 - Threshold Optimization (Best ROC-AUC Model)\nFind max-F1 threshold and recall>=0.80 threshold with highest precision, then compare against default 0.5."),
    code(
        "best_model_name = eval_table['roc_auc'].idxmax()\n"
        "best_model = models[best_model_name]\n"
        "y_prob_best = model_eval[best_model_name]['y_prob']\n"
        "\n"
        "threshold_grid = np.arange(0.0, 1.01, 0.01)\n"
        "threshold_rows = []\n"
        "for thr in threshold_grid:\n"
        "    y_pred_thr = (y_prob_best >= thr).astype(int)\n"
        "    threshold_rows.append({\n"
        "        'threshold': thr,\n"
        "        'precision': precision_score(y_test, y_pred_thr, zero_division=0),\n"
        "        'recall': recall_score(y_test, y_pred_thr, zero_division=0),\n"
        "        'f1': f1_score(y_test, y_pred_thr, zero_division=0),\n"
        "    })\n"
        "threshold_df = pd.DataFrame(threshold_rows)\n"
        "max_f1_threshold = float(threshold_df.loc[threshold_df['f1'].idxmax(), 'threshold'])\n"
        "recall_target = 0.80\n"
        "eligible = threshold_df[threshold_df['recall'] >= recall_target].sort_values(['precision', 'threshold'], ascending=[False, True])\n"
        "recall80_threshold = float(eligible.iloc[0]['threshold']) if not eligible.empty else 0.5\n"
        "\n"
        "def metric_at_threshold(threshold: float):\n"
        "    y_pred = (y_prob_best >= threshold).astype(int)\n"
        "    return {\n"
        "        'threshold': threshold,\n"
        "        'accuracy': accuracy_score(y_test, y_pred),\n"
        "        'precision': precision_score(y_test, y_pred, zero_division=0),\n"
        "        'recall': recall_score(y_test, y_pred, zero_division=0),\n"
        "        'f1': f1_score(y_test, y_pred, zero_division=0),\n"
        "        'roc_auc': roc_auc_score(y_test, y_prob_best),\n"
        "        'avg_precision': average_precision_score(y_test, y_prob_best),\n"
        "        'brier': brier_score_loss(y_test, y_prob_best),\n"
        "        'confusion_matrix': confusion_matrix(y_test, y_pred)\n"
        "    }\n"
        "\n"
        "threshold_analysis = pd.DataFrame([\n"
        "    metric_at_threshold(0.5),\n"
        "    metric_at_threshold(max_f1_threshold),\n"
        "    metric_at_threshold(recall80_threshold),\n"
        "])\n"
        "threshold_analysis.index = ['default_0.5', 'max_f1', 'recall_ge_0.80']\n"
        "print('Best model:', best_model_name)\n"
        "print('Max-F1 threshold:', max_f1_threshold)\n"
        "print('Recall>=0.80 threshold:', recall80_threshold)\n"
        "print(threshold_analysis[['threshold', 'accuracy', 'precision', 'recall', 'f1']])\n"
    ),
    md("## Step 3 - Required Plots\nPlot ROC and PR curves for all models, confusion matrix per model, and calibration diagnostics for the best model."),
    code(
        "plt.figure(figsize=(10, 6))\n"
        "for name, info in model_eval.items():\n"
        "    fpr, tpr, _ = roc_curve(y_test, info['y_prob'])\n"
        "    plt.plot(fpr, tpr, label=f\"{name} (AUC={info['roc_auc']:.3f})\")\n"
        "plt.plot([0, 1], [0, 1], 'k--', label='Random')\n"
        "plt.title('Stage 4 ROC Curves - All Models')\n"
        "plt.xlabel('False Positive Rate')\n"
        "plt.ylabel('True Positive Rate')\n"
        "plt.legend()\n"
        "save_plot('stage4_roc_curves_all_models')\n"
        "plt.show()\n"
        "\n"
        "plt.figure(figsize=(10, 6))\n"
        "for name, info in model_eval.items():\n"
        "    precision, recall, _ = precision_recall_curve(y_test, info['y_prob'])\n"
        "    plt.plot(recall, precision, label=f\"{name} (AP={info['avg_precision']:.3f})\")\n"
        "plt.title('Stage 4 Precision-Recall Curves - All Models')\n"
        "plt.xlabel('Recall')\n"
        "plt.ylabel('Precision')\n"
        "plt.legend()\n"
        "save_plot('stage4_pr_curves_all_models')\n"
        "plt.show()\n"
        "\n"
        "for name, info in model_eval.items():\n"
        "    plt.figure(figsize=(10, 6))\n"
        "    sns.heatmap(info['confusion_matrix'], annot=True, fmt='d', cmap='Blues', cbar=False, label='Count')\n"
        "    plt.title(f'Stage 4 Confusion Matrix - {name}')\n"
        "    plt.xlabel('Predicted Label')\n"
        "    plt.ylabel('True Label')\n"
        "    plt.legend()\n"
        "    save_plot(f'stage4_confusion_matrix_{name}')\n"
        "    plt.show()\n"
        "\n"
        "frac_pos, mean_pred = calibration_curve(y_test, y_prob_best, n_bins=10)\n"
        "plt.figure(figsize=(10, 6))\n"
        "plt.plot(mean_pred, frac_pos, marker='o', label='Uncalibrated')\n"
        "plt.plot([0, 1], [0, 1], linestyle='--', label='Perfectly calibrated')\n"
        "plt.title(f'Stage 4 Reliability Diagram - {best_model_name}')\n"
        "plt.xlabel('Mean Predicted Probability')\n"
        "plt.ylabel('Fraction of Positives')\n"
        "plt.legend()\n"
        "save_plot('stage4_reliability_diagram_best_model')\n"
        "plt.show()\n"
        "\n"
        "calibrator = CalibratedClassifierCV(best_model, method='isotonic', cv=5)\n"
        "calibrator.fit(X_train_eng, y_train)\n"
        "y_prob_cal = calibrator.predict_proba(X_test_eng)[:, 1]\n"
        "brier_uncal = brier_score_loss(y_test, y_prob_best)\n"
        "brier_cal = brier_score_loss(y_test, y_prob_cal)\n"
        "print('Brier uncalibrated:', brier_uncal)\n"
        "print('Brier calibrated (isotonic):', brier_cal)\n"
    ),
    md("## Step 4 - Comparative Summary Table\nCreate a consolidated table with test metrics and CV ROC-AUC mean/std for all models."),
    code(
        "cv_lookup = cv_summary.set_index('model')[['roc_auc_mean', 'roc_auc_std']].rename(columns={'roc_auc_mean': 'cv_roc_auc_mean', 'roc_auc_std': 'cv_roc_auc_std'})\n"
        "name_map = {\n"
        "    'lr_l2': 'LR_L2', 'lr_l1': 'LR_L1', 'naive_bayes': 'NaiveBayes', 'knn': 'KNN',\n"
        "    'decision_tree_tuned': 'DecisionTree_Tuned', 'random_forest': 'RandomForest', 'xgboost': 'XGBoost', 'svm': 'SVM'\n"
        "}\n"
        "summary_rows = []\n"
        "for key, info in model_eval.items():\n"
        "    cv_key = name_map[key]\n"
        "    summary_rows.append({\n"
        "        'model': key,\n"
        "        'test_accuracy': info['accuracy'],\n"
        "        'test_precision': info['precision'],\n"
        "        'test_recall': info['recall'],\n"
        "        'test_f1': info['f1'],\n"
        "        'test_roc_auc': info['roc_auc'],\n"
        "        'test_avg_precision': info['avg_precision'],\n"
        "        'brier_score': info['brier'],\n"
        "        'cv_roc_auc_mean': cv_lookup.loc[cv_key, 'cv_roc_auc_mean'],\n"
        "        'cv_roc_auc_std': cv_lookup.loc[cv_key, 'cv_roc_auc_std'],\n"
        "    })\n"
        "comparative_table = pd.DataFrame(summary_rows).sort_values('test_roc_auc', ascending=False).reset_index(drop=True)\n"
        "print(comparative_table)\n"
    ),
    md("## Step 5 - Segment-wise Evaluation\nEvaluate the best model by borrower segment and flag recall below 0.60."),
    code(
        "best_threshold = max_f1_threshold\n"
        "y_pred_best_thr = (y_prob_best >= best_threshold).astype(int)\n"
        "segment_rows = []\n"
        "for seg in sorted(borrower_type_test.unique()):\n"
        "    mask = borrower_type_test == seg\n"
        "    y_true_seg = y_test[mask]\n"
        "    y_pred_seg = y_pred_best_thr[mask]\n"
        "    y_prob_seg = y_prob_best[mask]\n"
        "    segment_rows.append({\n"
        "        'borrower_type': seg,\n"
        "        'precision': precision_score(y_true_seg, y_pred_seg, zero_division=0),\n"
        "        'recall': recall_score(y_true_seg, y_pred_seg, zero_division=0),\n"
        "        'f1': f1_score(y_true_seg, y_pred_seg, zero_division=0),\n"
        "        'roc_auc': roc_auc_score(y_true_seg, y_prob_seg) if y_true_seg.nunique() > 1 else np.nan,\n"
        "    })\n"
        "segment_table = pd.DataFrame(segment_rows)\n"
        "print(segment_table)\n"
        "for _, r in segment_table.iterrows():\n"
        "    if r['recall'] < 0.60:\n"
        "        print(f\"FLAG: Recall below 0.60 for segment {r['borrower_type']}: {r['recall']:.3f}\")\n"
    ),
    md("## Step 6 - Select Final Best Model\nSelect best model using ROC-AUC primary criterion, average precision tiebreaker, and Brier score secondary consideration."),
    code(
        "best_candidates = comparative_table.sort_values(['test_roc_auc', 'test_avg_precision', 'brier_score'], ascending=[False, False, True])\n"
        "final_best_name = best_candidates.iloc[0]['model']\n"
        "best_model = models[final_best_name]\n"
        "print('Final selected best_model:', final_best_name)\n"
        "print(best_candidates.head(3))\n"
    ),
    md("## Save Stage 4 Outputs"),
    code(
        "stage4_output = {\n"
        "    **stage3,\n"
        "    'model_eval': model_eval,\n"
        "    'comparative_table': comparative_table,\n"
        "    'threshold_analysis': threshold_analysis,\n"
        "    'segment_table': segment_table,\n"
        "    'best_model_name': final_best_name,\n"
        "    'best_model': best_model,\n"
        "    'max_f1_threshold': max_f1_threshold,\n"
        "    'recall80_threshold': recall80_threshold,\n"
        "    'calibrated_brier': brier_cal,\n"
        "    'uncalibrated_brier': brier_uncal,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage4_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage4_output, f)\n"
        "print('Saved:', out_path)\n"
    ),
    md("## Stage 4 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 4 SUMMARY')\n"
        "print('- Evaluated all required models (excluding DT-overfit from main comparison).')\n"
        "print(f\"- Selected best model: {final_best_name}\")\n"
        "print(f\"- Max-F1 threshold: {max_f1_threshold:.2f}\")\n"
        "print(f\"- Recall>=0.80 threshold: {recall80_threshold:.2f}\")\n"
        "print(f\"- Comparative table shape: {comparative_table.shape}\")\n"
        "print(f\"- Segment table shape: {segment_table.shape}\")\n"
        "print(f\"- Saved outputs to: {out_path}\")\n"
        "print('=' * 70)\n"
    ),
]


stage5_cells = [
    md("# Stage 5 - Fairness and Bias Audit\nThis notebook computes group fairness metrics at the Stage 4 max-F1 threshold and documents disparity interpretation."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from sklearn.metrics import confusion_matrix, precision_score, recall_score\n"
        "\n"
        "BASE_DIR = Path.cwd().parent\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
    ),
    md("## Load Stage 4 Outputs"),
    code(
        "with open(PROCESSED_DIR / 'stage4_outputs.pkl', 'rb') as f:\n"
        "    stage4 = pickle.load(f)\n"
        "best_model = stage4['best_model']\n"
        "X_test_eng = stage4['X_test_eng']\n"
        "y_test = stage4['y_test']\n"
        "borrower_type_test = stage4['borrower_type_test']\n"
        "max_f1_threshold = stage4['max_f1_threshold']\n"
        "print('Loaded test shape:', X_test_eng.shape)\n"
        "print('Best model:', stage4['best_model_name'])\n"
    ),
    md("## Compute Group-wise Fairness Metrics\nUse predictions at max-F1 threshold to calculate predicted positive rate, TPR, FPR, and precision for each borrower type."),
    code(
        "y_prob_best = best_model.predict_proba(X_test_eng)[:, 1]\n"
        "y_pred_best = (y_prob_best >= max_f1_threshold).astype(int)\n"
        "\n"
        "rows = []\n"
        "for group in sorted(borrower_type_test.unique()):\n"
        "    mask = borrower_type_test == group\n"
        "    y_true_g = y_test[mask]\n"
        "    y_pred_g = y_pred_best[mask]\n"
        "    tn, fp, fn, tp = confusion_matrix(y_true_g, y_pred_g).ravel()\n"
        "    ppr = y_pred_g.mean()\n"
        "    tpr = tp / (tp + fn) if (tp + fn) > 0 else np.nan\n"
        "    fpr = fp / (fp + tn) if (fp + tn) > 0 else np.nan\n"
        "    prec = precision_score(y_true_g, y_pred_g, zero_division=0)\n"
        "    rows.append({'borrower_type': group, 'predicted_positive_rate': ppr, 'tpr_recall': tpr, 'fpr': fpr, 'precision': prec})\n"
        "\n"
        "fairness_table = pd.DataFrame(rows)\n"
        "print(fairness_table)\n"
    ),
    md("## Compute Disparity Ratios\nFor each fairness metric, compute highest/lowest ratio and flag values above 1.25."),
    code(
        "disparity_rows = []\n"
        "for metric in ['predicted_positive_rate', 'tpr_recall', 'fpr', 'precision']:\n"
        "    values = fairness_table[metric].dropna()\n"
        "    ratio = float(values.max() / values.min()) if values.min() > 0 else np.inf\n"
        "    disparity_rows.append({'metric': metric, 'high_low_ratio': ratio, 'flag_ratio_gt_1_25': ratio > 1.25})\n"
        "disparity_table = pd.DataFrame(disparity_rows)\n"
        "print(disparity_table)\n"
    ),
    md("## Fairness Interpretation\nInterpret whether disparity patterns are likely data-driven versus possible model over-penalisation."),
    code(
        "print('Interpretation:')\n"
        "print('- Compare fairness ratios with known synthetic-data default differences across borrower groups.')\n"
        "print('- If PPR/TPR/FPR disparities exceed 1.25 materially, this suggests meaningful group performance divergence.')\n"
        "print('- Divergence may partly reflect true base-rate differences, but elevated FPR for one group indicates possible over-penalisation risk that should be monitored in policy.')\n"
        "print('- This stage documents disparities only; no mitigation is applied by design.')\n"
    ),
    md("## Save Stage 5 Outputs"),
    code(
        "stage5_output = {\n"
        "    **stage4,\n"
        "    'y_pred_best': y_pred_best,\n"
        "    'y_prob_best': y_prob_best,\n"
        "    'fairness_table': fairness_table,\n"
        "    'disparity_table': disparity_table,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage5_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage5_output, f)\n"
        "print('Saved:', out_path)\n"
    ),
    md("## Stage 5 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 5 SUMMARY')\n"
        "print('- Completed fairness audit at max-F1 decision threshold.')\n"
        "print(f\"- Fairness table shape: {fairness_table.shape}\")\n"
        "print(f\"- Disparity table shape: {disparity_table.shape}\")\n"
        "print(f\"- Metrics flagged (>1.25 ratio): {int(disparity_table['flag_ratio_gt_1_25'].sum())}\")\n"
        "print(f\"- Saved outputs to: {out_path}\")\n"
        "print('=' * 70)\n"
    ),
]


stage6_cells = [
    md("# Stage 6 - Explainability and Output Report\nThis notebook computes SHAP explanations, builds per-applicant report generation, and prints natural-language summaries."),
    code(
        "from pathlib import Path\n"
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import shap\n"
        "\n"
        "BASE_DIR = Path.cwd().parent\n"
        "PROCESSED_DIR = BASE_DIR / 'data' / 'processed'\n"
        "PLOT_DIR = BASE_DIR / 'outputs' / 'plots' / 'stage6'\n"
        "PLOT_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "def save_plot(name: str):\n"
        "    path = PLOT_DIR / f'{name}.png'\n"
        "    plt.tight_layout()\n"
        "    plt.savefig(path, dpi=300, bbox_inches='tight')\n"
        "    print(f'Saved plot: {path}')\n"
    ),
    md("## Load Stage 5 Outputs"),
    code(
        "with open(PROCESSED_DIR / 'stage5_outputs.pkl', 'rb') as f:\n"
        "    stage5 = pickle.load(f)\n"
        "best_model = stage5['best_model']\n"
        "best_model_name = stage5['best_model_name']\n"
        "X_train_eng = stage5['X_train_eng']\n"
        "X_test_eng = stage5['X_test_eng']\n"
        "y_test = stage5['y_test']\n"
        "cluster_model = stage5['cluster_model']\n"
        "cluster_names = stage5['cluster_names']\n"
        "borrower_type_test = stage5['borrower_type_test']\n"
        "print('Best model:', best_model_name)\n"
        "print('X_test shape:', X_test_eng.shape)\n"
    ),
    md("## Step 1 - Compute SHAP Values\nUse model-appropriate explainer and compute SHAP values on the full test set."),
    code(
        "if best_model_name in ['random_forest', 'xgboost']:\n"
        "    explainer = shap.TreeExplainer(best_model)\n"
        "    shap_values = explainer.shap_values(X_test_eng)\n"
        "elif best_model_name in ['lr_l2', 'lr_l1']:\n"
        "    explainer = shap.LinearExplainer(best_model, X_train_eng)\n"
        "    shap_values = explainer.shap_values(X_test_eng)\n"
        "elif best_model_name == 'svm':\n"
        "    background = shap.sample(X_train_eng, 200, random_state=42)\n"
        "    explainer = shap.KernelExplainer(lambda x: best_model.predict_proba(pd.DataFrame(x, columns=X_test_eng.columns))[:, 1], background)\n"
        "    shap_values = explainer.shap_values(X_test_eng)\n"
        "else:\n"
        "    explainer = shap.Explainer(best_model, X_train_eng)\n"
        "    shap_values = explainer(X_test_eng).values\n"
        "\n"
        "if isinstance(shap_values, list):\n"
        "    shap_values = shap_values[1] if len(shap_values) > 1 else shap_values[0]\n"
        "print('SHAP values shape:', np.array(shap_values).shape)\n"
    ),
    md("## Step 2 - Global SHAP Plots\nGenerate beeswarm, bar summary, and dependence plots for top 3 global features."),
    code(
        "plt.figure(figsize=(10, 6))\n"
        "shap.summary_plot(shap_values, X_test_eng, show=False)\n"
        "plt.title('Stage 6 SHAP Beeswarm Summary')\n"
        "save_plot('stage6_shap_beeswarm')\n"
        "plt.show()\n"
        "\n"
        "plt.figure(figsize=(10, 6))\n"
        "shap.summary_plot(shap_values, X_test_eng, plot_type='bar', show=False)\n"
        "plt.title('Stage 6 SHAP Bar Summary')\n"
        "save_plot('stage6_shap_bar')\n"
        "plt.show()\n"
        "\n"
        "mean_abs_shap = np.abs(shap_values).mean(axis=0)\n"
        "top3_idx = np.argsort(mean_abs_shap)[-3:][::-1]\n"
        "top3_features = X_test_eng.columns[top3_idx].tolist()\n"
        "print('Top 3 SHAP features:', top3_features)\n"
        "\n"
        "for feat in top3_features:\n"
        "    plt.figure(figsize=(10, 6))\n"
        "    shap.dependence_plot(feat, shap_values, X_test_eng, show=False)\n"
        "    plt.title(f'Stage 6 SHAP Dependence - {feat}')\n"
        "    save_plot(f'stage6_shap_dependence_{feat}')\n"
        "    plt.show()\n"
    ),
    md("## Step 3 - Applicant Report Function\nCreate `generate_applicant_report(...)` with exact required output keys and confidence logic."),
    code(
        "feature_to_english = {col: col.replace('_', ' ').capitalize() for col in X_test_eng.columns}\n"
        "feature_to_english.update({\n"
        "    'utility_payment_ratio': 'Utility bill payment consistency',\n"
        "    'income_regularity_index': 'Income stability over 6 months',\n"
        "    'loan_to_income_ratio': 'Loan amount relative to repayment capacity',\n"
        "    'digital_footprint_density': 'Digital activity data completeness',\n"
        "    'upi_consistency_score': 'UPI usage consistency',\n"
        "    'financial_discipline_score': 'Financial discipline from psychometric answers',\n"
        "    'future_planning_score': 'Future planning orientation',\n"
        "    'risk_appetite_score': 'Risk aversion psychometric signal',\n"
        "})\n"
        "\n"
        "cluster_profiles = {int(k): v for k, v in cluster_names.items()}\n"
        "\n"
        "def risk_tier_from_probability(p):\n"
        "    if p < 0.30:\n"
        "        return 'Low'\n"
        "    if p <= 0.60:\n"
        "        return 'Medium'\n"
        "    return 'High'\n"
        "\n"
        "def generate_applicant_report(applicant_index, X_test_eng, shap_values, y_test, cluster_model, cluster_profiles):\n"
        "    row = X_test_eng.iloc[[applicant_index]]\n"
        "    row_vec = shap_values[applicant_index]\n"
        "    prob = float(best_model.predict_proba(row)[:, 1][0])\n"
        "    sorted_idx = np.argsort(row_vec)\n"
        "    pos_idx = sorted_idx[:3]\n"
        "    neg_idx = sorted_idx[-3:][::-1]\n"
        "    top_pos = [feature_to_english.get(X_test_eng.columns[i], X_test_eng.columns[i]) for i in pos_idx]\n"
        "    top_neg = [feature_to_english.get(X_test_eng.columns[i], X_test_eng.columns[i]) for i in neg_idx]\n"
        "    missing_flags = int(row['upi_data_missing'].iloc[0] + row['rent_data_missing'].iloc[0] + row['ecomm_data_missing'].iloc[0])\n"
        "    density = float(row['digital_footprint_density'].iloc[0])\n"
        "    if density >= 0.8 and row['upi_data_missing'].iloc[0] == 0 and row['ecomm_data_missing'].iloc[0] == 0:\n"
        "        confidence = 'High'\n"
        "    elif density < 0.4 or missing_flags >= 2:\n"
        "        confidence = 'Low'\n"
        "    else:\n"
        "        confidence = 'Medium'\n"
        "    cluster_id = int(cluster_model.predict(row[stage5['clustering_features']])[0])\n"
        "    return {\n"
        "        'borrower_id': int(X_test_eng.index[applicant_index]),\n"
        "        'default_probability': round(prob, 4),\n"
        "        'risk_tier': risk_tier_from_probability(prob),\n"
        "        'actual_outcome': int(y_test.iloc[applicant_index]),\n"
        "        'top_3_positive_factors': top_pos,\n"
        "        'top_3_negative_factors': top_neg,\n"
        "        'data_confidence_flag': confidence,\n"
        "        'cluster_id': cluster_id,\n"
        "        'cluster_profile_name': cluster_profiles.get(cluster_id, 'Unknown Cluster Profile'),\n"
        "    }\n"
        "\n"
        "print('Feature mapping coverage:', len(feature_to_english), 'features mapped.')\n"
    ),
    md("## Step 4 - Waterfall Plots\nGenerate SHAP waterfall plots for one defaulter and one non-defaulter."),
    code(
        "defaulter_idx = int(np.where(y_test.values == 1)[0][0])\n"
        "non_defaulter_idx = int(np.where(y_test.values == 0)[0][0])\n"
        "\n"
        "base_val = explainer.expected_value\n"
        "if isinstance(base_val, (list, np.ndarray)):\n"
        "    base_val = float(np.array(base_val).reshape(-1)[-1])\n"
        "\n"
        "for idx, label in [(defaulter_idx, 'defaulter_example'), (non_defaulter_idx, 'non_defaulter_example')]:\n"
        "    exp = shap.Explanation(values=shap_values[idx], base_values=base_val, data=X_test_eng.iloc[idx], feature_names=X_test_eng.columns)\n"
        "    plt.figure(figsize=(10, 6))\n"
        "    shap.waterfall_plot(exp, max_display=12, show=False)\n"
        "    plt.title(f'Stage 6 Waterfall Plot - {label}')\n"
        "    save_plot(f'stage6_waterfall_{label}')\n"
        "    plt.show()\n"
        "print('Chosen indices:', {'defaulter': defaulter_idx, 'non_defaulter': non_defaulter_idx})\n"
    ),
    md("## Step 5 - Natural Language Summary Function\nCreate `generate_nl_summary(report_dict)` and demonstrate it on the same two applicants."),
    code(
        "def generate_nl_summary(report_dict):\n"
        "    risk = report_dict['risk_tier']\n"
        "    borrower_type = borrower_type_test.loc[report_dict['borrower_id']] if report_dict['borrower_id'] in borrower_type_test.index else 'unknown'\n"
        "    pos = report_dict['top_3_positive_factors'][:2]\n"
        "    neg = report_dict['top_3_negative_factors'][:2]\n"
        "    confidence = report_dict['data_confidence_flag']\n"
        "    if risk == 'Low':\n"
        "        recommendation = 'Recommended for approval'\n"
        "    elif risk == 'Medium':\n"
        "        recommendation = 'Recommended for manual review'\n"
        "    else:\n"
        "        recommendation = 'Recommended for rejection'\n"
        "    return (\n"
        "        f\"This {borrower_type} borrower is assessed as {risk} risk. \"\n"
        "        f\"The strongest protective factors are {pos[0]} and {pos[1]}. \"\n"
        "        f\"The strongest risk-elevating factors are {neg[0]} and {neg[1]}. \"\n"
        "        f\"Data confidence is {confidence}, which indicates the reliability of observed digital and behavioral inputs. \"\n"
        "        f\"{recommendation}.\"\n"
        "    )\n"
        "\n"
        "report_def = generate_applicant_report(defaulter_idx, X_test_eng, shap_values, y_test, cluster_model, cluster_profiles)\n"
        "report_non = generate_applicant_report(non_defaulter_idx, X_test_eng, shap_values, y_test, cluster_model, cluster_profiles)\n"
        "print('Defaulter report:', report_def)\n"
        "print('Defaulter NL summary:', generate_nl_summary(report_def))\n"
        "print('\\nNon-defaulter report:', report_non)\n"
        "print('Non-defaulter NL summary:', generate_nl_summary(report_non))\n"
    ),
    md("## Save Stage 6 Outputs"),
    code(
        "stage6_output = {\n"
        "    **stage5,\n"
        "    'shap_values': shap_values,\n"
        "    'top3_features': top3_features,\n"
        "    'defaulter_report': report_def,\n"
        "    'non_defaulter_report': report_non,\n"
        "}\n"
        "out_path = PROCESSED_DIR / 'stage6_outputs.pkl'\n"
        "with open(out_path, 'wb') as f:\n"
        "    pickle.dump(stage6_output, f)\n"
        "print('Saved:', out_path)\n"
    ),
    md("## Stage 6 Summary"),
    code(
        "print('=' * 70)\n"
        "print('STAGE 6 SUMMARY')\n"
        "print('- Computed SHAP values and generated global/local explainability outputs.')\n"
        "print(f\"- SHAP matrix shape: {np.array(shap_values).shape}\")\n"
        "print(f\"- Top global SHAP features: {top3_features}\")\n"
        "print(f\"- Example reports generated for borrower IDs: {report_def['borrower_id']}, {report_non['borrower_id']}\")\n"
        "print(f\"- Saved outputs to: {out_path}\")\n"
        "print('=' * 70)\n"
    ),
]


def main():
    notebooks = {
        "stage1_feature_engineering.ipynb": stage1_cells,
        "stage2_clustering.ipynb": stage2_cells,
        "stage3_model_training.ipynb": stage3_cells,
        "stage4_evaluation.ipynb": stage4_cells,
        "stage5_fairness_audit.ipynb": stage5_cells,
        "stage6_explainability.ipynb": stage6_cells,
    }
    for name, cells in notebooks.items():
        write_nb(NB_DIR / name, cells)
        print(f"Wrote {name} with {len(cells)} cells")


if __name__ == "__main__":
    main()
